"use client";

import { useRef, type RefObject } from "react";
import { FileText, Loader2 } from "lucide-react";
import { animate, stagger } from "animejs";

import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/theme-toggle";
import { cn } from "@/lib/utils";

interface ChatSidebarProps {
  uploading: boolean;
  uploadError: string | null;
  dragActive: boolean;
  sources: string[];
  fileInputRef: RefObject<HTMLInputElement | null>;
  onDragActiveChange: (active: boolean) => void;
  onFiles: (files: FileList | null) => void;
}

export function ChatSidebar({
  uploading,
  uploadError,
  dragActive,
  sources,
  fileInputRef,
  onDragActiveChange,
  onFiles,
}: ChatSidebarProps) {
  const pillsRef = useRef<HTMLUListElement>(null);
  const prevCount = useRef(0);

  if (sources.length > prevCount.current && pillsRef.current) {
    const added = Array.from(pillsRef.current.children).slice(prevCount.current);
    if (added.length) {
      animate(added, {
        opacity: [0, 1],
        scale: [0.85, 1],
        duration: 380,
        delay: stagger(60),
        ease: "outBack",
      });
    }
  }
  prevCount.current = sources.length;

  return (
    <aside className="w-80 shrink-0 border-r border-border bg-sidebar p-6 flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="h-8 w-8 rounded-lg bg-primary text-primary-foreground flex items-center justify-center text-sm font-semibold shadow-sm">
            D
          </div>
          <h1 className="text-lg font-semibold tracking-tight">DocChat</h1>
        </div>
        <ThemeToggle />
      </div>
      <p className="text-sm text-muted-foreground -mt-4">
        RAG-powered document Q&amp;A — runs local embeddings, answers only from your files.
      </p>

      <div
        onDragOver={(e) => {
          e.preventDefault();
          onDragActiveChange(true);
        }}
        onDragLeave={() => onDragActiveChange(false)}
        onDrop={(e) => {
          e.preventDefault();
          onDragActiveChange(false);
          onFiles(e.dataTransfer.files);
        }}
        onClick={() => fileInputRef.current?.click()}
        className={cn(
          "cursor-pointer rounded-xl border-2 border-dashed p-7 text-center text-sm transition-colors",
          dragActive
            ? "border-primary bg-accent"
            : "border-border hover:border-primary/50 hover:bg-accent/40"
        )}
      >
        {uploading ? (
          <Loader2 className="mx-auto mb-2 size-6 animate-spin text-primary" />
        ) : (
          <FileText className="mx-auto mb-2 size-6 text-muted-foreground" />
        )}
        {uploading ? "Processing…" : "Drop a PDF or .txt file, or click to browse"}
        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf,.txt,.md"
          multiple
          className="hidden"
          onChange={(e) => onFiles(e.target.files)}
        />
      </div>

      {uploadError && <p className="text-sm text-destructive">{uploadError}</p>}

      {sources.length > 0 && (
        <div>
          <h2 className="text-xs font-medium uppercase tracking-wide text-muted-foreground mb-2.5">
            Loaded documents
          </h2>
          <ul ref={pillsRef} className="flex flex-wrap gap-1.5 text-sm">
            {sources.map((s) => (
              <li key={s}>
                <Badge variant="secondary" className="max-w-full truncate font-medium">
                  {s}
                </Badge>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="mt-auto text-xs text-muted-foreground leading-relaxed">
        Embeddings run locally (Xenova/all-MiniLM-L6-v2). Answers generated by Claude, grounded
        strictly in retrieved chunks.
      </div>
    </aside>
  );
}
